### ISSUE TITLE
Docker Cannot Run Container

### ISSUE THREAD

**Issue by zluckytraveler** [davidk/docker-discord#3]
There are issues when trying to run the container. 

```
Lucky@p8-6 ~ % docker run --privileged \
-v /tmp/.X11-unix:/tmp/.X11-unix \
--device /dev/snd \
-v discordSettings:/home/discord \
-v /dev/shm:/dev/shm:z \
-v /etc/localtime:/etc/localtime:ro \
-v /var/run/dbus:/var/run/dbus \
-v /var/run/user/$(id -u)/bus:/var/run/user/1000/bus \
-e DBUS_SESSION_BUS_ADDRESS="unix:path=/var/run/user/1000/bus" \
-v /var/run/user/$(id -u)/pulse:/var/run/user/1000/pulse \
-e PULSE_SERVER="unix:/run/user/1000/pulse/native" \
-e DISPLAY=unix$DISPLAY \
--rm \
--group-add $(getent group audio | cut -d: -f3) \
keyglitch/discord:stable
zsh: command not found: getent
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
```

**Comment by davidk** [comment]
Hello,
It looks like the `getent` command does not exist on the system this container is running under. If this is a Linux system, the command should usually be available and return the ID for the audio user:

```bash 
$ getent group audio
audio:x:29:
```

Under other systems like OS X, this may not be the case. This container may not run properly even if this issue is resolved, since the `run` command assumes a Linux environment

**Comment by davidk** [comment]
Closing this issue as settled. Please feel free to follow up if you have any questions even though this has changed to closed. Thanks.
